### ISSUE TITLE
snpguest kbs-attest

### ISSUE THREAD

**Issue by tylerfanelli** [virtee/snpguest#15]
@larrydewey @DGonzalezVillal 

What do you think about an `snpguest kbs-attest` command?

Prospective usage:

`snpguest kbs-attest $WORKLOAD_ID $SERVER_URL`

snpguest would fetch the attestation report from the PSP and facilitate an attestation context for the workload pointed to by `WORKLOAD_ID` for the attestation server at `SERVER_URL`.

**Comment by larrydewey** [comment]
I think this would be pretty cool! I am assuming the `$WORKLOAD_ID` in this case would be a RATs claim?
