### ISSUE TITLE
Invalid cert type while trying to generate an certificate

### ISSUE THREAD

**Issue by DiWangShePi** [virtee/snpguest#20]
I ran into a bit of a problem when I tried to generate a PEM certificate using the following command
```
$ sudo ./snpguest certificates PEM certs
ERROR: Invalid cert type
Error: Invalid cert type
```
Then I change the format and met the same problem
```
$ sudo ./snpguest certificates DER certs
ERROR: Invalid cert type
Error: Invalid cert type
```
I'm not quite sure if I read the tutorial wrong, but that seems to be how he wrote it
```
$ sudo ./snpguest certificates -h
snpguest-certificates 0.3.0
Certificates command to request cached certificates from the AMD PSP

USAGE:
    snpguest certificates <encoding> <certs-dir>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    <encoding>     Specify encoding to use for certificates. [PEM | DER]
    <certs-dir>    Directory to store certificates in. Required if requesting an extended-report.
```

**Comment by sza-1** [comment]
This command does not generate certificates. It simply extracts the existing certificates (ASK, ARK and VCEK) from the CPU certificates cache. You have to import these certificates first with `snphost`.

**Comment by DiWangShePi** [comment]
Got it. Thanks.

**Comment by tylerfanelli** [comment]
@DiWangShePi You can use the `fetch` subcommands to fetch the CA and VCEK certs, then use `import` to store them to the PSP.
