### ISSUE TITLE
Why is `request_file` required to get an attestation report

### ISSUE THREAD

**Issue by cowbon** [virtee/snpguest#25]
Hi there,

I'm trying to play around with the tool, and compare it with [AMDESE/sev-guest](https://github.com/AMDESE/sev-guest), yet the documentation of the command *snpguest report* looks confusing. According to the README, User can pass 64 bytes of data in any file format into $REQUEST_FILE in order to use that data to request the attestation report. Alternatively, the user can use the `--random` flag to generate and use random data for `request_data`. It sounds optional in nature, and [sev-guest-get-report](https://github.com/AMDESE/sev-guest/blob/main/src/get-report.c) does not require it. However, the command must be specified as `snpguest report $ATT_REPORT_PATH $REQUEST_FILE [-v, --vmpl] $VMPL [-r, --random] [-p, --platform]`. That means the user must provide a source of hash even they wish snpguest to generate random data for them. Is there any reason why this is needed?

**Comment by tylerfanelli** [comment]
Hi! The `$REQUEST_FILE` argument works two different ways, depending on if `--random` is specified or not:

`--random` is **enabled**: The 64 byte request data will be randomly generated and **written to** `$REQUEST_FILE`
`--random` is **disabled**: The 64 byte request data will be **read from** `$REQUEST_FILE` (nothing is written to `$REQUEST_FILE` in this scenario).

**Comment by cowbon** [comment]
Hi @tylerfanelli, thanks for your response! However the next thing would be using the attestation report to get the VCEK. I first ran the command `./snpguest report $ATT_REPORT_PATH $REQUEST_FILE --random`, then `snpguest fetch vcek PEM Milan $CERTS_DIR $ATT_REPORT_PATH`. It resulted in the following error
```
thread 'main' panicked at 'Failed to parse the certificate: ErrorStack([Error { code: 218529960, library: "asn1 encoding routines", function: "asn1_check_tlen", reason: "wrong tag", file: "crypto/asn1/tasn_dec.c", line: 1149 }, Error { code: 218595386, library: "asn1 encoding routines", function: "asn1_item_embed_d2i", reason: "nested asn1 error", file: "crypto/asn1/tasn_dec.c", line: 309, data: "Type=X509" }])', src/certs.rs:130:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Switching `ENCODING` from PEM to DER was working, however the same issue happens again when running `snpguest verify attestation $CERTS_DIR $ATT_REPORT_PATH `. Is there anything I missed?

**Comment by tylerfanelli** [comment]
It seems that the PEM decoding of the VCEK is having some problems. Does `verify attestation` also fail with `Failed to parse the certificate`?

**Comment by cowbon** [comment]
Hi @tylerfanelli, is there a way to skip `$REQUEST_FILE` at all? I found the attestation report output is quite different from what I get from [sev-guest-get-report](https://github.com/AMDESE/sev-guest/blob/main/src/get-report.c). Everything such as chip ID, boot loader version, does not match what `sev-guest-get-report $ATT_REPORT_PATH` provides. Why is the difference?

**Comment by tylerfanelli** [comment]
sev-guest is for legacy SEV, this tool is for SEV-SNP. There are major differences between the two.

**Comment by cowbon** [comment]
No I mean why attestation report is wrong with VirTEE, and why do I ever need a request data if I just want to get an attestation report?

**Comment by cowbon** [comment]
> It seems that the PEM decoding of the VCEK is having some problems. Does `verify attestation` also fail with `Failed to parse the certificate`?

Yes. But if I use the attestation report from `sev-guest-get-report`, it's working properly. I can use the attestation report from such tool to request DER version of the  VCEK from VirTEE, then use it to validate the cert chain and the attestation report. It's not the case if I use the attestation report from VirTEE instead

**Comment by cowbon** [comment]
> sev-guest is for legacy SEV, this tool is for SEV-SNP. There are major differences between the two.
No I mean why the content of the attestation report is wrong with VirTEE, and why do I ever need a request data if I just want to get an attestation report?

**Comment by tylerfanelli** [comment]
Hmm, maybe there's a problem in the attestation report's serialization.

@DGonzalezVillal can you take a look at this problem? It seems there's something wrong with the attestation report's format fetched from `snpguest report`. It should match that of `sev-guest-get-report`, no?

**Comment by larrydewey** [comment]
@tylerfanelli We ran a `git bisect`, and It looks like there was a change introduced in your hyper-v commit which we all missed during the review process.

It looks like the change switched from writing serialized binary data to the human-readable code. 

https://github.com/virtee/snpguest/blob/245247eba7547c08038f49c7e3bb182423f25a46/src/report.rs#L132-L135

**Comment by larrydewey** [comment]
@cowbon Can you pull the updates merged into main and see if this fixes your issue?

**Comment by cowbon** [comment]
Yes, it is working right now. But I would also recommend making `request_data` optional before closing the issue.

**Comment by DGonzalezVillal** [comment]
> Yes, it is working right now. But I would also recommend making `request_data` optional before closing the issue.

The request_data isn't really an optional field. Although sev-guest does not require request_data, it still passes request data to the report request. The only difference is that sev-guest fills the request data with 0's if you don't pass any data in. With snpguest you're allowed to pass in random data if you don't want to pass your own data. We make you specify a file because we want you to know what data is being passed into the request. It works as an additional security check.

**Comment by larrydewey** [comment]
@cowbon like @DGonzalezVillal mentioned above, it is a required field as per the [SEV-SNP ABI Specification](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf#page=43) (see Table 20).
