### ISSUE TITLE
Crates.io support?

### ISSUE THREAD

**Issue by CookieComputing** [virtee/snpguest#31]
Hi there,

I noticed there wasn't a crate on crates.io yet: https://crates.io/search?q=snpguest, are there plans to add one soon?

On a related note, `snphost` is also out of date: https://crates.io/crates/snphost/versions, the latest being `0.1.2`, while there is [2.0.0](https://github.com/virtee/snphost/releases/tag/v0.2.0) which was released two weeks ago. Will that be updated too?

**Comment by larrydewey** [comment]
We are in the process of getting a release for `snpguest`, and I will be cutting new releases for the other products on crates.io now that I have been given permission for them.

**Comment by larrydewey** [comment]
@CookieComputing took a bit of work to sort out the dependency issues. I have published both `snpguest` and `snphost`.
