### ISSUE TITLE
Error: VCEK did NOT sign the Attestation Report!

### ISSUE THREAD

**Issue by pegahnikbakht** [virtee/snpguest#32]
Hi,

Each time I fetch the VCEK with the command below: 
`./snpguest fetch vcek pem milan ./certs attestation-report.bin`
a new VCEK is derived which is different from previous ones, is it normal?

Also when I try to verify the report with VCEK it fails with the following error:
`Error: VCEK did NOT sign the Attestation Report!`
Any idea? how to make sure the right VCEK is derived from the server? 

Regards,
Pegah

**Comment by larrydewey** [comment]
Hey @pegahnikbakht can you verify the firmware version you are using by running the following command and pasting the data? I am wondering if you have an out-of-date firmware.

```sh
dmesg | grep "ccp"
```

**Comment by tylerfanelli** [comment]
The VCEK shouldn't change if your attestation report remains the same... the VCEK fetching data is derived from `attestation_report.bin`... are you fetching new attestation reports as well?

**Comment by larrydewey** [comment]
> I'm using ubuntu 22.04. This is the output of dmesg on the host:
> 
> ```
> [   15.127673] ccp 0000:47:00.1: no command queues available
> [   15.128070] ccp 0000:47:00.1: sev enabled
> [   15.128072] ccp 0000:47:00.1: psp enabled
> [   15.178054] ccp 0000:47:00.1: SEV firmware update successful
> [   16.115717] ccp 0000:47:00.1: SEV API:1.51 build:3
> [   16.115721] ccp 0000:47:00.1: SEV-SNP API:1.51 build:3
> ```
> 
> I'm using the snpguest tool from main branch.

![image](https://github.com/virtee/snpguest/assets/41640198/71153aed-2dc5-4c8b-87aa-c0a99cd09af9)

Your API version is out-of-date, which may be causing the discrepancy. You can download the newer version of the firmware from:

https://www.amd.com/en/developer/sev.html

**Comment by pegahnikbakht** [comment]
@tylerfanelli My attestation report is the same (I fetch it only once) but each time I run this command a new VCEK is derived.

`./snpguest fetch vcek pem milan ./certs attestation-report.bin`

**Comment by pegahnikbakht** [comment]
After firmware update I needed to use snphost to fetch and import certs again, now it works fine, thanks for the help.
