### ISSUE TITLE
Support VLEK in `snpguest certificates`

### ISSUE THREAD

**Issue by gianlucascopelliti** [virtee/snpguest#36]
Hi,

I was trying to get certificates for a SNP instance running in AWS, but I experienced the following error when running the `snpguest certificates` command:

```
ERROR: Invalid cert type
Error: Invalid cert type
```

Upon further inspection, I found out that the error was coming from [this line](https://github.com/virtee/snpguest/blob/439f4446202567c8fbe89e9322667443427a43ea/src/certs.rs#L148), where indeed the VLEK certificate type (guid `a8074bc2-a25a-483e-aae6-39c045a0b8a1`) is not checked (actually, this is not even present in the `CertType` struct of the `sev` crate).

I also tried fetching the VLEK manually and passing it as input to `snpguest verify attestation` instead of the VCEK, and everything works correctly. However, this command would also require slight changes to, e.g., look for the VLEK in case the VCEK is not present.

**Comment by tylerfanelli** [comment]
@DGonzalezVillal Is this something we could accommodate? I assume some `sev` changes would also need to be added.

**Comment by DGonzalezVillal** [comment]
@tylerfanelli yes. After I'm done with the pre-attestation work (ID-BLOCK and measurement) I was going to start working on VLEK support

**Comment by larrydewey** [comment]
@gianlucascopelliti VLEK support was merged upstream for SEV, and this will be covered in the VLEK additional support for snpguest.
