### ISSUE TITLE
'report' command does not work on Azure confidential VMs with SEV-SNP

### ISSUE THREAD

**Issue by berrange** [virtee/snpguest#5]
On the Azure platform, after creating a confidential VM with their SEV-SNP offering, it is not possible to fetch the attestation report with the `snpguest` tool:

```
# ./target/debug/snpguest report
ERROR: failed to open SEV firmware device.
because: No such file or directory (os error 2)
Error: failed to open SEV firmware device.

Caused by:
    No such file or directory (os error 2)
```

The cause is the missing `/dev/snp-guest` device which we would expect to be provided by the `sev-guest` kernel module

```
# modprobe sev-guest
modprobe: ERROR: could not insert 'sev_guest': No such device
```

IIUC, this is an intentional limitation of the Azure SEV-SNP CVM feature. The only documented way of getting an attestation report within Azure is to read the report pre-provided by the HCL via a vTPM non-volatile variable as documented in:

https://github.com/Azure/confidential-computing-cvm-guest-attestation/blob/main/cvm-guest-attestation.md

```
$ tpm2_nvread -C o 0x01400001 > ./snp_report.bin
$ dd skip=32 bs=1 count=1184 if=./snp_report.bin of=./guest_report.bin
```

I've done this and the `guest_report.bin` file can successfully be parsed by `snpguest`:

```
# ./target/debug/snpguest display report -a /root/guest_report.bin 

Attestation Report (1184 bytes):
Version:                      2
Guest SVN:                    4

    Guest Policy (196639):
    ABI Major:     0
    ABI Minor:     31
    SMT Allowed:   1
    Migrate MA:    0
    Debug Allowed: 0
    Single Socket: 0

...snip...
```

I think that it is desirable if the `snpguest report` command can be made to "do the right thing(TM)" when on Azure. eg, first try the `/dev/sev-guest` approach, but if this device doesn't exist, then query the tpm2 to see if variable with handle 0x01400001 exists, and if so try to extract the report from that. I've not yet found documentation of the full TPM variable data blob, beyond the fact that the SNP report is at offset 32, but I did find some other code that gives names to data at various offsets:

https://github.com/kinvolk/azure-cvm-tooling/blob/main/az-snp-vtpm/src/hcl.rs#L40

```
pub struct HclAttestationHeader {
    pub signature: u32,
    pub version: u32,
    pub report_size: u32,
    pub request_type: IgvmReportType,
    pub reserved: [u32; 4], //<- this looks wrong
}

pub struct IgvmRequestData {
    pub data_size: u32,
    pub version: u32,
    pub report_type: IgvmReportType,
    pub report_data_hash_type: IgvmHashType,
    pub variable_data_size: u32,
    pub variable_data: [u8; 0],
}

pub struct HclAttestationReport {
    pub header: HclAttestationHeader,
    pub hw_report: AttestationReport,
    pub hcl_data: IgvmRequestData,
}
```

So I'd say for logic we should

- Check if TPM variable 0x01400001 exists
- Check the header signature == "HCLA"
- Check the header version == 1
- Check the report type == 2 (SNP)

at that point we can be pretty confident that the report data is a SEV-SNP attestation report and proceed to extract it.

**Comment by tylerfanelli** [comment]
@berrange Investigating now. I assume this should be tested on the RHEL 9.2 CVM Preview Image?

**Comment by berrange** [comment]
> @berrange Investigating now. I assume this should be tested on the RHEL 9.2 CVM Preview Image?

Yep, that's what I've been testing

**Comment by berrange** [comment]
I notice that the 'report' command lets you include 'report data', optionally using random bytes for this. 

In the Azure scenario we don't have that option, the Attestation report in the vTPM is generated by their paravisor and invariant thereafter.

For getting the VCEK on azure there's a special URL endpoint to talk to at http://169.254.169.254/metadata/THIM/amd/certification

On Linux KVM hosts which uses SVSM, the existing 'snpguest report' should work for getting the VMPL 1 attestation report.  SVSM, however, will also expose a VMPL 0 attestation report which can be acquired via a new ioctl on /dev/sev-guest per a proposal at https://lore.kernel.org/linux-coco/20230607150646.97208-1-dovmurik@linux.ibm.com/T/#t
