### ISSUE TITLE
./snpguest report command reports an error

### ISSUE THREAD

**Issue by My-avenge** [virtee/snpguest#54]
I reported the following error when I executed the snpguest report command：My running environment is an instance of AMD SEV-SNP supported by Google Cloud. The cpu is AMD Milan and the system is Ubuntu20.04 LTS.
```
root@snp-instance:/home/snp/snpguest/target/release# ./snpguest report report.bin request-file.txt --random
ERROR: unable to fetch attestation report
because: Firmware Error Encountered: I/O Error
because: I/O Error
because: Inappropriate ioctl for device (os error 25)
Error: unable to fetch attestation report

Caused by:
    0: Firmware Error Encountered: I/O Error
    1: I/O Error
    2: Inappropriate ioctl for device (os error 25)
```

**Comment by tylerfanelli** [comment]
Although you're running as a confidential guest, there are kernel patches needed to interact with the secure processor. These patches would not available in Ubuntu 20.04 LTS at the moment. You would most likely need to update your kernel to one with these patches.

**Comment by tylerfanelli** [comment]
@larrydewey Can you provide a link to the latest guest kernel branch?

**Comment by larrydewey** [comment]
Hey @tylerfanelli it looks like 98543c2aa64942a32cf623f2b8b3ddd01ef515c2 is the latest (https://github.com/AMDESE/linux/tree/snp-guest-latest).

**Comment by tylerfanelli** [comment]
@My-avenge try installing that kernel that Larry pointed to. Closing this issue for now. Can re-open if the problem persists.
