### ISSUE TITLE
-bash: snpguest: command not found

### ISSUE THREAD

**Issue by ccylance** [virtee/snpguest#62]
I installed snpguest according to the instructions in the building section of the readme and did not receive any error messages. However, when I entered the command "snpguest --help", it prompted an error saying "-bash: snpguest: command not found". Can someone please help me with this?

**Comment by ccylance** [comment]
I fixed it by using cargo install snpguest

**Comment by tylerfanelli** [comment]
Hi @ccylance

It seems that you may not be specifying the exact path of the snpguest binary.

From the root of the snpguest directory:
```
$ cargo build -r
$ ./target/release/snpguest --help
```

If you want to just run `snpguest --help` (or any other subcommand), copy the binary to `/usr/bin`.

From the root of the snpguest directory:
```
$ cargo build -r
$ cp ./target/release/snpguest /usr/bin
$ snpguest --help
```

**Comment by tylerfanelli** [comment]
> I fixed it by using cargo install snpguest

Great. If you were compiling locally, the above instructions would work for you.
