### ISSUE TITLE
Any ways to generate GOSVW and HOST_DATA by snpguest?

### ISSUE THREAD

**Issue by qiankehan** [virtee/snpguest#65]
Hi developers,
I am testing the SEV_SNP feature for qemu and libvirt.
For the **guest-visible-workarounds** and **host-data** field in qemu, I don't know how to fill them. [Qemu doc](https://www.qemu.org/docs/master/interop/qemu-qmp-ref.html#qapidoc-2290) says it is from ‘GOSVW’ parameter of the SNP_LAUNCH_START command, and  the ‘HOST_DATA’ parameter of the SNP_LAUNCH_FINISH.
So is there any ways to generate these data by snpguest?

**Comment by tylerfanelli** [comment]
`host_data` is a field in the attestation report. It contains the bytes that were set by SNP_LAUNCH_FINISH. The "Secrets Page" contains the data set in GOSVW from SNP_LAUNCH_START.
