### ISSUE TITLE
Clap dependency restrictive semver?

### ISSUE THREAD

**Issue by CookieComputing** [virtee/snpguest#68]
Hi folks,

I was taking a look at the `Cargo.toml` file, and noticed the [`clap dependency`](https://github.com/virtee/snpguest/blob/main/Cargo.toml#L22) has a rather restrictive semver constraint ("<4.5", specifically). I was wondering if there was a particular reason for this? I was surprised to see the restriction against "<4.5", when it seems like the repo would probably build fine with 4.5? I've noticed that this is also present in the [`snphost`](https://github.com/virtee/snphost/blob/main/Cargo.toml#L30) repo as well.

Is this for MSRV reasons? I think Clap 4.4 has an MSRV of [1.70](https://github.com/clap-rs/clap/blob/v4.4.18/Cargo.toml#L17), while Clap 4.5 has an MSRV of [1.74](https://github.com/clap-rs/clap/blob/v4.5.16/Cargo.toml#L18). However, since you folks have committed your lockfile, I think should that be sufficient in imposing a version constraint without applying modifiers on the version number. Let me know your thoughts!

**Comment by tylerfanelli** [comment]
@larrydewey I think you added the `clap` dependency in favor of `structopt`, was there a reason for this?

**Comment by CookieComputing** [comment]
Closing since https://github.com/virtee/snpguest/pull/69 was checked in
