### ISSUE TITLE
Typo for --guest_field_select option in snpguest key command

### ISSUE THREAD

**Issue by aadomn** [virtee/snpguest#75]
In the README, it is mentioned that the `snpguest key` command has a `--guest_field_select` option to specify which Guest **Field** Select bits to enable for the key derivation.
However, when running the following command on an SNP guest
`snpguest key derived-key.bin vcek --guest_field_select 100001 --guest_svn 2 --tcb_version 1 --vmpl 3`
I get the following error
```
error: unexpected argument '--guest_field_select' found

  tip: a similar argument exists: '--guest_file_select'

Usage: snpguest key <key-path|root-key-select|--vmpl <vmpl>|--guest_file_select <######>|--guest_svn <GSVN>|--tcb_version <TCBV>>

```
Works fine when using `--guest_file_select` though.

**Comment by tylerfanelli** [comment]
Fixed in version 0.8.0.
